name: Android UBDiag Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'
      - name: Build Dev
        uses: UbiqueInnovation/actions-android/buildAndUpload@main
        with:
          projectKey: 'UB'
          configuration: 'dev'
          app: 'AppName'
          appModuleDirectory: './app'
          gradleProps: '-PubiqueMavenUrl=${{ secrets.UBIQUE_MAVEN_URL }} -PubiqueMavenUser=${{ secrets.UBIQUE_MAVEN_USERNAME }} -PubiqueMavenPass=${{ secrets.UBIQUE_MAVEN_PASSWORD }} -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }}'
          buildNumber: ${{ github.run_number }}
          backendEndpoint: ${{ secrets.UBDIAG_UPLOAD_URL }}
