name: Build and Upload to UBDiag

on:
  push:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
    secrets:
      UPLOAD_KEY_STORE_PASSWORD:
        required: true
      UPLOAD_KEY_PASSWORD:
        required: true
      ANDROID_PUBLISHER_CREDENTIALS:
        required: true


jobs:
  build_dev:
    name: Build ${{ inputs.flavor }} Flavor
    runs-on: ubuntu-latest
    steps:
      # Checkout repository and submodules
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.ANDROID_JENKINS_PAT }}
          submodules: 'recursive'

      # Set build variables for reuse in multiple steps
      - name: Set Build Variables
        id: vars
        run: |
          echo ::set-output name=build_uuid::$(cat /proc/sys/kernel/random/uuid)
          echo ::set-output name=web_icon::${{ github.workspace }}/app/tmp_icon_large_for_backend.png
          echo ::set-output name=flavor_capitalized::${${{ inputs.flavor }}~}

      # Setup the build environment with Java 11 and the Zulu OpenJDK
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Setup the build environment with Gradle
      - name: Build and publish app
        uses: gradle/gradle-build-action@v2
        with:
          # Cache entries are not shared among branches. To reduce the amount of cache writes, only allow the main branch to write cache entries and let other branches read them
          # https://github.com/gradle/gradle-build-action#only-write-to-the-cache-from-the-default-branch
          cache-read-only: ${{ github.ref_name != 'main' }}
          arguments: |
            publish${{ steps.vars.outputs.flavor_capitalized }}ReleaseUploadBundle
            -PubiqueMavenUrl=${{ secrets.UBIQUE_MAVEN_URL }}
            -PubiqueMavenUser=${{ secrets.UBIQUE_MAVEN_USERNAME }}
            -PubiqueMavenPass=${{ secrets.UBIQUE_MAVEN_PASSWORD }}
            -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }}
        env:
          UPLOAD_KEY_STORE_PASSWORD: ${{ secrets.UPLOAD_KEY_STORE_PASSWORD }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
