name: Deploy on Kubernetes Cluster
on:
  workflow_call:

    inputs:
      ref:
        required: true
        type: string
        description: tag or branch name
      project:
        required: true
        type: string
        description: e.g. swisstopo, schweizmobil, ...
      module:
        required: true
        type: string
        description: e.g. importer
      target:
        required: true
        type: string
        description: dev|prod

    secrets:
      acr_registry:
        required: true
      acr_username:
        required: true
      acr_password:
        required: true
      artifactory_user:
        required: true
      artifactory_password:
        required: true
      az_service_principal:
        required: true

env:
  PARENT_POM: ${{ inputs.project }}-backend/pom.xml
  APP_DIRECTORY: ${{ inputs.project }}-backend/${{ inputs.project }}-${{ inputs.module }}
  APP_NAME: ${{ inputs.project }}-${{ inputs.module }}
  ACR_REGISTRY: ${{ secrets.acr_registry }}
  ACR_USERNAME: ${{ secrets.acr_username }}
  ACR_PASSWORD: ${{ secrets.acr_password }}
  SECRET: ub-acr-secret
  UB_ARTIFACTORY_USER: ${{ secrets.artifactory_user}}
  UB_ARTIFACTORY_PASSWORD: ${{ secrets.artifactory_password }}
  CLUSTER_NAME: ub-kub-dev
  CLUSTER_RESOURCE_GROUP: ub-schweiz-cluster
  NAMESPACE: ${{ inputs.project }}
  CONFIG_MAP: ${{ inputs.project }}-${{ inputs.module }}-${{ inputs.target }}-config
  AZ_SERVICE_PRINCIPAL: ${{ secrets.az_service_principal }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ env.AZ_SERVICE_PRINCIPAL }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Create namespace (if it doesn't exist)
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -

      - name: Create configmap
        run: |
          kubectl create configmap --namespace ${{ env.NAMESPACE }} ${{ env.CONFIG_MAP }} --from-file ${{ env.APP_DIRECTORY }}/conf/${{ inputs.target }} --dry-run=client -o json | kubectl apply -f -

      - name: Create image pull secret for ACR
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ env.ACR_REGISTRY }}
          container-registry-username: ${{ env.ACR_USERNAME }}
          container-registry-password: ${{ env.ACR_PASSWORD }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}

      - name: Apply Deployment and Service config
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ env.APP_DIRECTORY }}/manifests/${{ inputs.target }}/deployment.yaml
            ${{ env.APP_DIRECTORY }}/manifests/${{ inputs.target }}/service.yaml
          images: |
            ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:${{ inputs.ref }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}

      - name: Apply Ingress config
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ env.APP_DIRECTORY }}/manifests/${{ inputs.target }}/ingress.yaml
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ingress-basic