name: Runs Maven Install
on:
  workflow_call:

    inputs:
      ref_name:
        required: true
        type: string
        description: tag or branch name
      app_name:
        required: true
        type: string
      app_directory:
        required: true
        type: string
      java_version:
        default: '17'
        type: string
        required: false

    secrets:
      artifactory_user:
        required: true
      artifactory_password:
        required: true
      acr_registry:
        required: true
      acr_username:
        required: true
      acr_password:
        required: true

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
    -   name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref_name }}
    -   name: Git Status
        run: git status
    -   name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: ${{ inputs.java_version }}
            distribution: 'adopt'
            server-id: ubique-artifactory
            server-username: ARTIFACTORY_USER
            server-password: ARTIFACTORY_PASSWORD
    -   name: Cache Maven packages
        uses: actions/cache@v2
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
    -   name: Build and push docker
        run: |
            mvn --batch-mode compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build \
            -f ${{ inputs.app_directory }}/pom.xml \
            -Dimage=${{ secrets.acr_registry }}/${{ inputs.app_name }}:${{ inputs.ref_name }} \
            -Djib.from.image=eclipse-temurin:${{ inputs.java_version }} \
            -Djib.to.auth.username=${{ secrets.acr_username }} \
            -Djib.to.auth.password=${{ secrets.acr_password }} \
            -Djib.container.volumes=/config/ \
            -Djib.container.jvmFlags=-XX:MinRAMPercentage=60.0,-XX:MaxRAMPercentage=80.0

