name: Runs Maven Install
on:
  workflow_call:

    inputs:
      parent_pom:
        required: true
        type: string
      java_version:
        default: '17'
        type: string
        required: false

    secrets:
      artifactory_user:
        required: true
      artifactory_password:
        required: true

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      -   uses: actions/checkout@v2
      -   name: Set up JDK
          uses: actions/setup-java@v2
          with:
              java-version: ${{ inputs.java_version }}
              distribution: 'adopt'
              server-id: ubique-artifactory
              server-username: ${{ secrets.artifactory_user}}
              server-password: ${{ secrets.artifactory_password }}
      -   name: Cache Maven packages
          uses: actions/cache@v2
          with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
      -   name: Get version
          env:
              REF_NAME: ${{ inputs.ref_name }}
          run: echo "VERSION=${REF_NAME/v/}" >> $GITHUB_ENV
      -   name: Set versions
          run: mvn -f ${{ inputs.parent_pom }} versions:set -DnewVersion=$VERSION
      -   name: Commit versions
          run: mvn -f ${{ inputs.parent_pom }} versions:commit
      -   name: Build with Maven
          run: mvn --batch-mode --update-snapshots install -f ${{ inputs.parent_pom }}
