name: Runs Maven Install
on:
  workflow_call:

    inputs:
      parent_pom:
        required: true
        type: string
      java_version:
        default: '17'
        type: string
        required: false

    secrets:
      artifactory_user:
        required: true
      artifactory_password:
        required: true

env:
    ARTIFACTORY_USER: ${{ secrets.artifactory_user}}
    ARTIFACTORY_PASSWORD: ${{ secrets.artifactory_password }}

jobs:
  build:
      name: Build Project
      runs-on: ubuntu-latest
      steps:
      -   uses: actions/checkout@v2
      -   name: Set up JDK
          uses: actions/setup-java@v2
          with:
              java-version: ${{ inputs.java_version }}
              distribution: 'adopt'
              server-id: ubique-artifactory
              server-username: ARTIFACTORY_USER
              server-password: ARTIFACTORY_PASSWORD
      -   name: Cache Maven packages
          uses: actions/cache@v2
          with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
      -   name: Build with Maven
          run: mvn --batch-mode --update-snapshots install -f ${{ inputs.parent_pom }}
