name: Deploy Maven Package
on:
  workflow_call:

    inputs:
      parent_pom:
        required: true
        type: string
      package_version:
        type: string
        required: true
      java_version:
        default: '17'
        type: string
        required: false

    secrets:
      artifactory_user:
        required: true
      artifactory_password:
        required: true

env:
    ARTIFACTORY_USER: ${{ secrets.artifactory_user}}
    ARTIFACTORY_PASSWORD: ${{ secrets.artifactory_password }}

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      -   uses: actions/checkout@v2
      -   name: Set up JDK
          uses: actions/setup-java@v2
          with:
              java-version: ${{ inputs.java_version }}
              distribution: 'adopt'
              server-id: ubique-artifactory
              server-username: ARTIFACTORY_USER
              server-password: ARTIFACTORY_PASSWORD
      -   name: Cache Maven packages
          uses: actions/cache@v2
          with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
      -   name: Set versions
          run: mvn -f ${{ inputs.parent_pom }} versions:set -DnewVersion=${{ inputs.package_version }} 
      -   name: Commit versions
          run: mvn -f ${{ inputs.parent_pom }} versions:commit 
      -   name: Deploy package
          run: mvn -f ${{ inputs.parent_pom }} package deploy
